### ISSUE TITLE
Do you still have your CraftBukkit modifications?

### ISSUE THREAD

**Issue by Johnanater** [myers/Pogic#1]
Hey, I know this is a super old project, but do you still have your CraftBukkit modifications? The one you uploaded on GitHub got DMCA'd when CraftBukkit was originally taken down.

https://github.com/myers/CraftBukkit

Thanks!

**Comment by myers** [comment]
Maybe?  Here is a zip of what I think was my checkout of that fork: http://gir.maski.org/CraftBukkit-myers.zip

**Comment by myers** [comment]
@Johnanater Let me know if it works, if not I may have time to dig some more.

**Comment by Johnanater** [comment]
It looks like that's it, thank you so much!
